#!/bin/bash
# Background process to allow udev to continue
# Sleep to wait for keyboard being activated

### HEADER ###

if ! pgrep -x "i3" > /dev/null
then
  exit 0
fi

LOCKFILE="/var/lock/`basename $0`"
LOCKFD=99

# PRIVATE
_lock()             { flock -$1 $LOCKFD; }
_no_more_locking()  { _lock u; _lock xn && rm -f $LOCKFILE; }
_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; }

# ON START
_prepare_locking

# PUBLIC
exlock_now()        { _lock xn; }  # obtain an exclusive lock immediately or fail
exlock()            { _lock x; }   # obtain an exclusive lock
shlock()            { _lock s; }   # obtain a shared lock
unlock()            { _lock u; }   # drop a lock

### BEGIN OF SCRIPT ###

# Simplest example is avoiding running multiple instances of script.
exlock_now || exit 0

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

su wilvin -c "numlockx on"
su wilvin -c "xmodmap -e 'clear Lock'"
su wilvin -c "xmodmap -e 'keycode 0x42=Escape'"
su wilvin -c "/usr/bin/notify-send 'Keyboard plugged in'"

_no_more_locking
