setopt HIST_IGNORE_SPACE
alias jrnl=" jrnl"
alias spac="sudo pacman"

export JAVA_HOME="/usr/lib/jvm/java-7-openjdk"
export PATH="$PATH:$HOME/.local/bin/"

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
