setopt HIST_IGNORE_SPACE
alias jrnl=" jrnl"
alias spac="sudo pacman"
alias stopvpn="sudo systemctl stop openvpn-client@mullvad_nl.service"
alias startvpn="sudo systemctl start openvpn-client@mullvad_nl.service"
alias wifi_restart="sudo systemctl restart wpa_supplicant@wlp4s0.service"

alias start="sudo systemctl start $1"
alias status="sudo systemctl status $1"
alias restart="sudo systemctl restart $1"
alias stop="sudo systemctl stop $1"

alias journal="sudo journalctl -u $@"
alias startns="dotnet run -p ./NSInzichtRijstijlBackend/NSInzichtRijstijlBackend.csproj"

alias nlssh="ssh drnevil@149.210.189.232 -p 50683"
alias genshortcuts="python $HOME/.dotfiles/scripts/Shortcuts.py && echo \"Shortcuts generated!\" && source ~/.zshrc"

alias bootwin="i3-msg 'exec urxvtc -e bash -c $HOME/.dotfiles/scripts/bootwin.sh'"
#virsh -c qemu:///system start win10'"
alias startwin="i3-msg 'exec virt-viewer -c qemu:///system win10'"

#export {http,https,ftp}_proxy="http://127.0.0.1:8123"
export ANDROID_HOME="/opt/android-sdk"
export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_191"
export PATH="$PATH:/opt/android-sdk/platform-tools:$HOME/.dotnet/tools:$JAVA_HOME/bin:$HOME/.local/bin/:$HOME/.gem/ruby/2.4.0/bin:$HOME/.npm-global/bin"

export VIMCONFIG=~/.config/nvim
export VIMDATA=~/.local/share/nvim
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim
alias vi=nvim

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[ -f $HOME/.fzf.zsh ] && source ~/.fzf.zsh
[ -f $HOME/.dotfiles/theming/env_vars.sh ] && source $HOME/.dotfiles/theming/env_vars.sh
